In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Concatenating Data

In [3]:
!ls ../raw_data

gleague.csv       international.csv nba.csv           ncaa.csv

In [6]:
gl = pd.read_csv('../raw_data/gleague.csv')
it = pd.read_csv('../raw_data/international.csv')
nba = pd.read_csv('../raw_data/nba.csv')
ncaa = pd.read_csv('../raw_data/ncaa.csv')

In [7]:
gl.shape, it.shape, nba.shape, ncaa.shape

((4621, 63), (122607, 63), (7652, 63), (74972, 63))

In [14]:
gl['Competition'] = 'G-League'
gl.head()

,index,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
0,90,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,G-League,UTA,2008,18,640.5,123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,604,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,G-League,UTA,2010,38,1046.6,149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1138,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,G-League,SXF,2012,39,1133.9,142,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1568,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,G-League,MNE,2013,38,792.2,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,173,5,Jermareo Davidson,/player/Jermareo-Davidson/Summary/5,G-League,SXF,2008,6,188.6,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
it['Competition'] = 'International'
it.head()

,index,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
0,59984,1,Greg Oden,/player/Greg-Oden/Summary/1,International,JIA,2016,25,669.1,128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,82104,2,Carl Landry,/player/Carl-Landry/Summary/2,International,JIL,2018,36,1229.9,344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27690,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,International,RETH,2013,13,312.7,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38966,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,International,NaN,2014,10,291.2,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53356,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,International,PAI,2015,7,162.3,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
nba.head()

,index,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
0,2019,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2009,61,1313.9,198,...,16.2,1.0,4.2,19.2,-5.3,1.5,116.1,103.7,12.4,471.2
1,2571,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2010,21,501.8,92,...,17.8,0.9,7.2,20.6,-5.6,1.5,118.5,97.5,21.0,238.5
2,4517,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,MIA,2014,23,212.1,27,...,16.9,1.7,5.1,16.0,-5.5,1.4,107.6,104.5,3.1,50.9
3,1629,2,Carl Landry,/player/Carl-Landry/Summary/2,NBA,HOU,2008,42,711.4,135,...,8.9,1.3,0.7,18.9,-1.7,1.6,130.6,102.4,28.2,286.1
4,1998,2,Carl Landry,/player/Carl-Landry/Summary/2,NBA,HOU,2009,69,1466.7,240,...,11.9,0.9,1.5,18.0,-2.9,1.5,123.3,105.3,18.0,485.4

In [19]:
ncaa['Competition'] = 'NCAA'
ncaa.head()

,index,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
0,8989,1,Greg Oden,/player/Greg-Oden/Summary/1,NCAA,OSU,2007,32,925.0,189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,206,2,Carl Landry,/player/Carl-Landry/Summary/2,NCAA,PU,2005,25,757.0,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7007,2,Carl Landry,/player/Carl-Landry/Summary/2,NCAA,PU,2006,5,123.0,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8842,2,Carl Landry,/player/Carl-Landry/Summary/2,NCAA,PU,2007,34,1034.0,219,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,529,3,Gabe Pruitt,/player/Gabe-Pruitt/Summary/3,NCAA,USC,2005,29,871.0,124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df = pd.concat([gl, it, nba, ncaa])
df.shape

(209852, 63)

In [80]:
df.head()

,index,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
0,8989,1,Greg Oden,/player/Greg-Oden/Summary/1,NCAA,OSU,2007,32,925.0,189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2009,61,1313.9,198,...,16.2,1.0,4.2,19.2,-5.3,1.5,116.1,103.7,12.4,471.2
2,2571,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2010,21,501.8,92,...,17.8,0.9,7.2,20.6,-5.6,1.5,118.5,97.5,21.0,238.5
3,4517,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,MIA,2014,23,212.1,27,...,16.9,1.7,5.1,16.0,-5.5,1.4,107.6,104.5,3.1,50.9
4,59984,1,Greg Oden,/player/Greg-Oden/Summary/1,International,JIA,2016,25,669.1,128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df.replace('-', None)
df.replace('NaN', None)

,level_0,index,Id,Player,Link,Competition,Team,Season,GP,MIN,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
0,0,8989,1,Greg Oden,/player/Greg-Oden/Summary/1,NCAA,OSU,2007,32,925.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2019,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2009,61,1313.9,...,16.2,1.0,4.2,19.2,-5.3,1.5,116.1,103.7,12.4,471.2
2,1,2571,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2010,21,501.8,...,17.8,0.9,7.2,20.6,-5.6,1.5,118.5,97.5,21.0,238.5
3,2,4517,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,MIA,2014,23,212.1,...,16.9,1.7,5.1,16.0,-5.5,1.4,107.6,104.5,3.1,50.9
4,0,59984,1,Greg Oden,/player/Greg-Oden/Summary/1,International,JIA,2016,25,669.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209847,122602,118004,172607,Will Mcaloney,/player/Will-Mcaloney/Summary/172607,International,NLEX,2020,7,97.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209848,122603,121136,172628,Kent Salado,/player/Kent-Salado/Summary/172628,International,BGK,2020,5,13.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209849,122604,120107,172801,Prince Rivero,/player/Prince-Rivero/Summary/172801,International,ROS,2020,5,31.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209850,122605,122518,175140,Adrian Riesgo,/player/Adrian-Riesgo/Summary/175140,International,GIJ,2020,1,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209851,122606,121007,175382,Yaroslav Nuagu,/player/Yaroslav-Nuagu/Summary/175382,International,LK2,2020,3,31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning NaNs

In [51]:
df = pd.read_csv('../raw_data/all.csv')
df.shape

/Users/nloureiro/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (49,50,51,52,53,54,55,56,57,59,61,62) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(209852, 63)

In [68]:
df.replace('-', None, inplace=True)
df["Team"].fillna("Unknown", inplace = True)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209852 entries, 0 to 209851
Data columns (total 63 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   index        209852 non-null  int64
 1   Id           209852 non-null  int64
 2   Player       209852 non-null  object
 3   Link         209852 non-null  object
 4   Competition  209852 non-null  object
 5   Team         209852 non-null  object
 6   Season       209852 non-null  int64
 7   GP           209852 non-null  int64
 8   MIN          209852 non-null  float64
 9   FGM          209852 non-null  int64
 10  FGA          209852 non-null  int64
 11  FG%          209852 non-null  float64
 12  3PM          209852 non-null  int64
 13  3PA          209852 non-null  int64
 14  3P%          209852 non-null  float64
 15  FTM          209852 non-null  int64
 16  FTA          209852 non-null  int64
 17  FT%          209852 non-null  float64
 18  TOV          209852 non-null  int64
 19  PF           209852 non-null  int64
 20  ORB          209852 non-null  int64
 21  DRB          209852 non-null  int64
 22  REB          209852 non-null  int64
 23  AST          209852 non-null  int64
 24  STL          209852 non-null  int64
 25  BLK          209852 non-null  int64
 26  PTS          209852 non-null  int64
 27  DDBL         3678 non-null    float64
 28  TDBL         3678 non-null    float64
 29  40PTS        3678 non-null    float64
 30  20REB        3678 non-null    float64
 31  20AST        3678 non-null    float64
 32  5STL         3678 non-null    float64
 33  5BLK         3678 non-null    float64
 34  HIGHGAME     3678 non-null    float64
 35  TECHS        3678 non-null    float64
 36  HOB          3678 non-null    float64
 37  AST/TO       3678 non-null    float64
 38  STL/TO       3678 non-null    float64
 39  FT/FGA       3678 non-null    float64
 40  W-S          3678 non-null    float64
 41  L-S          3678 non-null    float64
 42  WIN%         3678 non-null    float64
 43  OWS          3678 non-null    float64
 44  DWS          3678 non-null    float64
 45  WS           3678 non-null    float64
 46  TS%          7652 non-null    float64
 47  EFG%         7652 non-null    float64
 48  TOTALS%      7652 non-null    float64
 49  ORB%         7425 non-null    object
 50  DRB%         7568 non-null    object
 51  TRB%         7591 non-null    object
 52  AST%         7465 non-null    object
 53  TOV%         7488 non-null    object
 54  STL%         7391 non-null    object
 55  BLK%         7151 non-null    object
 56  USG%         7632 non-null    object
 57  PPS          7536 non-null    object
 58  ORTG         7652 non-null    float64
 59  DRTG         7607 non-null    object
 60  EDIFF        7652 non-null    float64
 61  FIC          7607 non-null    object
 62  PER          7627 non-null    object
dtypes: float64(28), int64(19), object(16)
memory usage: 100.9+ MB

In [79]:
df[df['Competition'] == 'NBA']

,index,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
1,2019,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2009,61,1313.9,198,...,16.2,1.0,4.2,19.2,-5.3,1.5,116.1,103.7,12.4,471.2
2,2571,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,POR,2010,21,501.8,92,...,17.8,0.9,7.2,20.6,-5.6,1.5,118.5,97.5,21.0,238.5
3,4517,1,Greg Oden,/player/Greg-Oden/Summary/1,NBA,MIA,2014,23,212.1,27,...,16.9,1.7,5.1,16.0,-5.5,1.4,107.6,104.5,3.1,50.9
8,1629,2,Carl Landry,/player/Carl-Landry/Summary/2,NBA,HOU,2008,42,711.4,135,...,8.9,1.3,0.7,18.9,-1.7,1.6,130.6,102.4,28.2,286.1
9,1998,2,Carl Landry,/player/Carl-Landry/Summary/2,NBA,HOU,2009,69,1466.7,240,...,11.9,0.9,1.5,18.0,-2.9,1.5,123.3,105.3,18.0,485.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195307,7572,121522,Talen Horton-Tucker,/player/Talen-Horton-Tucker/Summary/121522,NBA,LAL,2020,6,81.2,14,...,15.9,4.7,1.2,19.3,-2.5,1.1,101.7,119.0,-17.3,19.8
195918,7155,121815,Ja Morant,/player/Ja-Morant/Summary/121815,NBA,MEM,2020,67,2074.2,447,...,17.0,1.3,0.8,25.9,5,1.3,108.9,113.1,-4.2,870.8
196249,7041,121978,Zhaire Smith,/player/Zhaire-Smith/Summary/121978,NBA,PHI,2019,6,110.6,14,...,13.8,0.9,1.4,16.8,0.6,1.2,102.5,117.6,-15.2,26
196251,7624,121978,Zhaire Smith,/player/Zhaire-Smith/Summary/121978,NBA,PHI,2020,7,32.3,3,...,13.6,4.4,NaN,19.7,-2.1,0.7,64.1,108.1,-44,0.8
197324,7326,122662,Jaxson Hayes,/player/Jaxson-Hayes/Summary/122662,NBA,NOP,2020,64,1079.7,174,...,13.4,1.1,4.3,15.1,-1.4,1.8,130.5,111.4,19.1,428.8

# Cleaning Advanced

In [90]:
df = pd.read_csv('../raw_data/all_clean.csv')
df.shape

(209852, 62)

In [93]:
df[df['Player'] == 'LeBron James']

,Id,Player,Link,Competition,Team,Season,GP,MIN,FGM,FGA,...,TOV%,STL%,BLK%,USG%,PPS,ORTG,DRTG,EDIFF,FIC,PER
2807,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2005,80,3388.0,795,1684,...,11.8,2.8,1.1,29.7,3.7,1.3,113.5,103.8,9.7,1613.2
2808,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2006,79,3361.3,875,1823,...,10.7,2.0,1.5,33.7,2.6,1.4,115.5,104.8,10.7,1600.8
2809,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2007,78,3190.3,772,1621,...,11.5,2.1,1.3,31.1,2.0,1.3,111.6,100.6,11.0,1383.1
2810,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2008,75,3026.8,794,1642,...,11.4,2.4,2.1,33.4,3.5,1.4,116.7,103.8,12.9,1627.1
2811,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2009,81,3054.0,789,1613,...,11.0,2.4,2.4,33.8,5.1,1.4,121.6,99.4,22.3,1801.2
2812,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2010,76,2965.6,768,1528,...,12.3,2.2,2.0,33.5,5.9,1.5,121.3,102.1,19.2,1787.9
2813,250,LeBron James,/player/LeBron-James/Summary/250,NBA,MIA,2011,79,3063.0,758,1484,...,13.8,2.1,1.3,31.5,2.8,1.4,116.3,101.9,14.4,1574.4
2814,250,LeBron James,/player/LeBron-James/Summary/250,NBA,MIA,2012,62,2326.2,621,1169,...,13.3,2.6,1.8,31.9,1.9,1.4,118.2,98.3,19.9,1301.5
2815,250,LeBron James,/player/LeBron-James/Summary/250,NBA,MIA,2013,76,2877.1,765,1354,...,12.4,2.4,1.9,30.1,5.0,1.5,124.7,101.4,23.3,1767.6
2816,250,LeBron James,/player/LeBron-James/Summary/250,NBA,MIA,2014,77,2901.9,767,1353,...,14.4,2.2,0.8,31.0,2.0,1.5,120.9,105.0,15.9,1576.9
2817,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2015,69,2493.4,624,1279,...,15.3,2.3,1.5,32.4,2.8,1.4,112.7,104.5,8.1,1240.0
2818,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2016,76,2708.6,737,1416,...,13.2,2.0,1.5,31.4,3.6,1.4,116.5,102.3,14.2,1471.9
2819,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2017,74,2794.6,736,1344,...,16.1,1.6,1.3,29.9,4.6,1.5,119.5,108.5,10.9,1662.4
2820,250,LeBron James,/player/LeBron-James/Summary/250,NBA,CLE,2018,82,3025.8,857,1580,...,16.1,1.9,2.0,31.6,5.0,1.4,118.3,109.2,9.1,1941.9
2821,250,LeBron James,/player/LeBron-James/Summary/250,NBA,LAL,2019,55,1937.4,558,1095,...,13.3,1.7,1.4,31.8,5.3,1.4,114.9,108.7,6.1,1205.0
2822,250,LeBron James,/player/LeBron-James/Summary/250,NBA,LAL,2020,67,2316.3,643,1303,...,15.1,1.6,1.4,31.6,8.4,1.3,115.6,106.5,9.1,1466.1

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209852 entries, 0 to 209851
Data columns (total 62 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Id           209852 non-null  int64
 1   Player       209852 non-null  object
 2   Link         209852 non-null  object
 3   Competition  209852 non-null  object
 4   Team         209852 non-null  object
 5   Season       209852 non-null  int64
 6   GP           209852 non-null  int64
 7   MIN          209852 non-null  float64
 8   FGM          209852 non-null  int64
 9   FGA          209852 non-null  int64
 10  FG%          209852 non-null  float64
 11  3PM          209852 non-null  int64
 12  3PA          209852 non-null  int64
 13  3P%          209852 non-null  float64
 14  FTM          209852 non-null  int64
 15  FTA          209852 non-null  int64
 16  FT%          209852 non-null  float64
 17  TOV          209852 non-null  int64
 18  PF           209852 non-null  int64
 19  ORB          209852 non-null  int64
 20  DRB          209852 non-null  int64
 21  REB          209852 non-null  int64
 22  AST          209852 non-null  int64
 23  STL          209852 non-null  int64
 24  BLK          209852 non-null  int64
 25  PTS          209852 non-null  int64
 26  DDBL         3678 non-null    float64
 27  TDBL         3678 non-null    float64
 28  40PTS        3678 non-null    float64
 29  20REB        3678 non-null    float64
 30  20AST        3678 non-null    float64
 31  5STL         3678 non-null    float64
 32  5BLK         3678 non-null    float64
 33  HIGHGAME     3678 non-null    float64
 34  TECHS        3678 non-null    float64
 35  HOB          3678 non-null    float64
 36  AST/TO       3678 non-null    float64
 37  STL/TO       3678 non-null    float64
 38  FT/FGA       3678 non-null    float64
 39  W-S          3678 non-null    float64
 40  L-S          3678 non-null    float64
 41  WIN%         3678 non-null    float64
 42  OWS          3678 non-null    float64
 43  DWS          3678 non-null    float64
 44  WS           3678 non-null    float64
 45  TS%          7652 non-null    float64
 46  EFG%         7652 non-null    float64
 47  TOTALS%      7652 non-null    float64
 48  ORB%         7425 non-null    float64
 49  DRB%         7568 non-null    float64
 50  TRB%         7591 non-null    float64
 51  AST%         7465 non-null    float64
 52  TOV%         7488 non-null    float64
 53  STL%         7391 non-null    float64
 54  BLK%         7151 non-null    float64
 55  USG%         7632 non-null    float64
 56  PPS          7536 non-null    float64
 57  ORTG         7652 non-null    float64
 58  DRTG         7607 non-null    float64
 59  EDIFF        7652 non-null    float64
 60  FIC          7607 non-null    float64
 61  PER          7627 non-null    float64
dtypes: float64(40), int64(18), object(4)
memory usage: 99.3+ MB